// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	corev1 "k8s.io/api/core/v1"

	mock "github.com/stretchr/testify/mock"

	rest "k8s.io/client-go/rest"

	types "k8s.io/apimachinery/pkg/types"

	v1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetAnnotationsOnPod provides a mock function with given fields: namespace, name
func (_m *Client) GetAnnotationsOnPod(namespace string, name string) (map[string]string, error) {
	ret := _m.Called(namespace, name)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string, string) map[string]string); ok {
		r0 = rf(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNetworkAttachmentDefinition provides a mock function with given fields: namespace, name
func (_m *Client) GetNetworkAttachmentDefinition(namespace string, name string) (*v1.NetworkAttachmentDefinition, error) {
	ret := _m.Called(namespace, name)

	var r0 *v1.NetworkAttachmentDefinition
	if rf, ok := ret.Get(0).(func(string, string) *v1.NetworkAttachmentDefinition); ok {
		r0 = rf(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.NetworkAttachmentDefinition)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPods provides a mock function with given fields: namespace
func (_m *Client) GetPods(namespace string) (*corev1.PodList, error) {
	ret := _m.Called(namespace)

	var r0 *corev1.PodList
	if rf, ok := ret.Get(0).(func(string) *corev1.PodList); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PodList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestClient provides a mock function with given fields:
func (_m *Client) GetRestClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// PatchPod provides a mock function with given fields: pod, patchType, patchData
func (_m *Client) PatchPod(pod *corev1.Pod, patchType types.PatchType, patchData []byte) error {
	ret := _m.Called(pod, patchType, patchData)

	var r0 error
	if rf, ok := ret.Get(0).(func(*corev1.Pod, types.PatchType, []byte) error); ok {
		r0 = rf(pod, patchType, patchData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnPod provides a mock function with given fields: pod, annotations
func (_m *Client) SetAnnotationsOnPod(pod *corev1.Pod, annotations map[string]string) error {
	ret := _m.Called(pod, annotations)

	var r0 error
	if rf, ok := ret.Get(0).(func(*corev1.Pod, map[string]string) error); ok {
		r0 = rf(pod, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
