---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ib-kubernetes
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ib-kubernetes
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch", "watch"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ib-kubernetes
roleRef:
  name: ib-kubernetes
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ib-kubernetes
    namespace: kube-system
---
# Runs daemon on the master node(s)
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ib-kubernetes
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      This deployment launches the ib-kubernetes daemon for Infiniband CNI.
spec:
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: ib-kubernetes
  template:
    metadata:
      labels:
        name: ib-kubernetes
        component: network
        type: infra
        kubernetes.io/os: "linux"
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: ib-kubernetes
      hostNetwork: true
      # required to be scheduled on a linux node with node-role.kubernetes.io/master label and
      # only one instance of ib-kubernetes pod per node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - ""
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - "linux"
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values:
                      - ""
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - "linux"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - ib-kubernetes
              topologyKey: kubernetes.io/hostname
      containers:
        - name: ib-kubernetes
          image: mellanox/ib-kubernetes
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/ib-kubernetes"]
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          env:
            - name: DAEMON_SM_PLUGIN
              valueFrom:
                configMapKeyRef:
                  name: ib-kubernetes-config
                  key: DAEMON_SM_PLUGIN
            - name: DAEMON_PERIODIC_UPDATE
              valueFrom:
                configMapKeyRef:
                  name: ib-kubernetes-config
                  key: DAEMON_PERIODIC_UPDATE
                  optional: true
            - name: GUID_POOL_RANGE_START
              valueFrom:
                configMapKeyRef:
                  name: ib-kubernetes-config
                  key: GUID_POOL_RANGE_START
                  optional: true
            - name: GUID_POOL_RANGE_END
              valueFrom:
                configMapKeyRef:
                  name: ib-kubernetes-config
                  key: GUID_POOL_RANGE_END
                  optional: true
            - name: UFM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_USERNAME
                  optional: true
            - name: UFM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_PASSWORD
                  optional: true
            - name: UFM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_ADDRESS
                  optional: true
            - name: UFM_HTTP_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_HTTP_SCHEMA
                  optional: true
            - name: UFM_PORT
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_PORT
                  optional: true
            - name: UFM_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: ib-kubernetes-ufm-secret
                  key: UFM_CERTIFICATE
                  optional: true
