// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import runtime "k8s.io/apimachinery/pkg/runtime"

// ResourceEvent is an autogenerated mock type for the ResourceEvent type
type ResourceEvent struct {
	mock.Mock
}

// GetResource provides a mock function with given fields:
func (_m *ResourceEvent) GetResource() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetResourceObject provides a mock function with given fields:
func (_m *ResourceEvent) GetResourceObject() runtime.Object {
	ret := _m.Called()

	var r0 runtime.Object
	if rf, ok := ret.Get(0).(func() runtime.Object); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.Object)
		}
	}

	return r0
}

// OnAdd provides a mock function with given fields: obj
func (_m *ResourceEvent) OnAdd(obj interface{}) {
	_m.Called(obj)
}

// OnDelete provides a mock function with given fields: obj
func (_m *ResourceEvent) OnDelete(obj interface{}) {
	_m.Called(obj)
}

// OnUpdate provides a mock function with given fields: oldObj, newObj
func (_m *ResourceEvent) OnUpdate(oldObj interface{}, newObj interface{}) {
	_m.Called(oldObj, newObj)
}
