on: [push, pull_request]
name: build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOARCH: ${{ matrix.goarch }}
        run: make build
