on: [push, pull_request]
name: build

permissions:
  contents: read

jobs:
  build:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-check-reusable.yml@main
    with:
      command: make build
