on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: lint
        run: make lint

      - name: test
        run: make test

  coverage:
    runs-on: ubuntu-latest
    name: coverage
    needs: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test with coverage
        run: make test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: cover.out
