on: [push, pull_request]
name: test

permissions:
  contents: read

jobs:
  test:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-check-reusable.yml@main
    with:
      command: |
        make lint
        make test
        make test-coverage
      coverage-file: cover.out
